documentation:
  - changed-files:
    - any-glob-to-any-file:
      - '**/*.md'
      - '!README.md'
      - 'install/**'
      - 'tutorial/**'
      - 'cheat-sheet/**'

enhancement:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**'
      - '.github/dependabot.yml'
      - '_config.yml'
      - 'Gemfile'
      - 'Gemfile.lock'
      - '.markdownlint.json'
