documentation:
  - any:
    - '**/*.md'
    - '!README.md'
    - 'install/**'
    - 'tutorial/**'
    - 'cheat-sheet/**'

enhancement:
  - any:
    - '.github/workflows/**'
    - '.github/dependabot.yml'
    - '_config.yml'
    - 'Gemfile'
    - 'Gemfile.lock'
    - '.markdownlint.json'
