title: LaTeX
email: resnikal71202@th-nuernberg.de
description: A guide on how to install an use LaTeX
theme: just-the-docs

url: https://resnikal71202.github.io/LaTeX

plugins:
  - jekyll-relative-links