name: Documentation Improvement
description: Suggest an improvement to the documentation
title: "[Docs]: "
labels: ["documentation", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to improve?
      placeholder: Tell us what could be better
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current State
      description: What does the documentation currently say or show?
      placeholder: Describe the current state
    validations:
      required: false

  - type: textarea
    id: proposed
    attributes:
      label: Proposed Change
      description: What would you like the documentation to say or show?
      placeholder: Describe your proposed change
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why is this change beneficial?
      placeholder: Explain why this would be an improvement
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or references
      placeholder: Screenshots, links, examples, etc.
    validations:
      required: false
